#!/bin/bash


#function for dims
dims()
{
  #count rows
  #reference for wc -l https://www.tecmint.com/wc-command-examples/
  rowNum="$(wc -l < $matrixFile)"

  #count the number of columns by counting elements in the first line of the matrixFile
  colNum=$( head -n 1 $matrixFile | wc -w)  

  echo -e "$rowNum $colNum"

}


transpose()
{

  cat "$matrixFile" > tempRow1$$

  #count the number of columns by counting elements in the first line of the matrixFile
  colNum=$( head -n 1 $matrixFile | wc -w) 
 
  #count rows
  #reference for wc -l https://www.tecmint.com/wc-command-examples/
  row="$(wc -l < tempRow1$$)"

  i=0
  while [ $i -lt $colNum ]
  do

    
    #increment counter
    i=$((i+1))
    #Transpose from tempRow1 to tempRow2 of the temp from PID
    cat tempRow1$$ | cut -f "$i" | tr '\n' '\t' | cut -f -"$row" >> tempRow2$$


  done
  cat tempRow2$$

  rm -f tempRow*
}

mean ()
{
  echo "in mean"

  tempMean="temporary mean file"
  #tempCol="temporary column file"

  i=0

   #count the number of columns by counting elements in the first line of the matrixFile
  colNum=$( head -n 1 $matrixFile | wc -w) 

  cat "$matrixFile" > tempCol

  #loop through each column
  while [[ $i -le $numCol ]]
  do
    #increment the counter
    i=$((i+1))

    count=0
    sum=0
    cut -f $i $matrixFile > $tempCol


    while read num
    do
       sum=`expr $sum + $num`
       count=`expr $count + 1`
       echo "sum = $sum"
    done <$tempCol

  #Equation given to us in program description
  mean=$(((sum + (count/2)*( (sum>0)*2-1 )) / count))

  echo "mean = $mean"
  echo "$mean" > "$tempMean"
  cat $tempMean | tr "\n" "\t" > "$tempRow"


  cat $tempMean

  

done

rm -f temp*
   

}

add()
{
  echo "in add"

}

multiply()
{
  echo "in multiply"

}

trapCatch()
{
  rm -f temp*
  exit 1
}

  #DIMS & TRANSPOSE & MEAN

  #Since dims and mean both only need one matrix will check to see if dims or mean was passed
  #as the first argument before checking the number of matrices passed
  if [ $1 = "dims" ] || [ $1 = "transpose" ] || [ $1 = "mean" ]
    then

      #print to stderr if too many arguments are passed in
      if (( $# > 2 ))
      then
          echo "Too many arguments for $1" 1>&2
          exit 1
      fi

      #check to see if anything was passed in with function name
      if [ $# -eq 1 ]
        then
           matrixFile=temp
           cat > $matrixFile

      fi
    

      #print to stderr if the file is not readable
      #source on how to tell a file is readable
      #https://askubuntu.com/questions/558977/checking-for-a-file-and-whether-it-is-readable-and-writable
      if [ ! -r $2 ]
      then
       echo "$2 is not a readable file" 1>&2
       exit 1
      fi


      if [ $# -gt 1 ]
      then
         matrixFile=$2
       fi


      if [ $1 = "dims" ]
      then
        dims $matrixFile
      fi

      if [ $1 = "mean" ]
      then
	      mean $matrixFile
      fi

      if [ $1 = "transpose" ]
      then
        transpose $matrixFile
      fi


    fi

    #ADD
    if [ $1 = "add" ]
    then

      #Check to see if enough arguments have been passed
      if [ $# -ne 3 ]
      then
        echo "Invalid number of arguments" 1>&2
        exit 1
      fi

      #Check to see that both files are readable
      if [ ! -r $2 ] || [ ! -r $3 ]
      then
        echo "One or more of your files are not readable" 1>&2
        exit 1
      fi

      if [ $# -eq 3 ]
      then
         matrixOne=$2
         matrixTwo=$3
      fi

      #grab row and column for each matrix                                                                
      colMatOne=$( head -n 1 $matrixOne | wc -w)  
      rowMatOne=$(wc -l < $matrixOne)
      colMatTwo=$( head -n 1 $matrixTwo | wc -w)                              
      rowMatTwo=$(wc -l < $matrixTwo)  

      #compare the rows and columns to make sure they are the same dimension
      if [ $colMatOne -ne $colMatTwo ] || [ $rowMatOne -ne $rowMatTwo ]
      then
         echo "Matrices not the same dimension" 1>&2
         exit 1
      fi

  add $matrixOne $matrixTwo
  fi

#trap trapCatch 
trap "rm -f $temp*;  exit 1" INT


rm -f temp*

